### ISSUE TITLE
xpp, sysfs: device_driver struct is now const

### ISSUE THREAD

**Issue by InterLinked1** [asterisk/dahdi-linux#63]
Build failure against mainline/next kernels, due to https://github.com/torvalds/linux/commit/d69d804845985c29ab5be5a4b3b1f4787893daf8:

```
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-pcm.o
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-sysfs.c:479:18: error: initialization of 'int (*)(struct device *, const struct device_driver *)' from incompatible pointer type 'int (*)(struct device *, struct device_driver *)' [-Werror=incompatible-pointer-types]
  479 |         .match = astribank_match,
      |                  ^~~~~~~~~~~~~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-sysfs.c:479:18: note: (near initialization for 'toplevel_bus_type.match')
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-sysfs.c:835:18: error: initialization of 'int (*)(struct device *, const struct device_driver *)' from incompatible pointer type 'int (*)(struct device *, struct device_driver *)' [-Werror=incompatible-pointer-types]
  835 |         .match = xpd_match,
      |                  ^~~~~~~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-sysfs.c:835:18: note: (near initialization for 'xpd_type.match')
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/vpmoct.o
cc1: all warnings being treated as errors
make[4]: *** [scripts/Makefile.build:244: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-sysfs.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-base.o
  LD [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/opvxa1200/opvxa1200.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs.o
  LD [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/dahdi_voicebus.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs-chan.o
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs.c:283:27: error: initialization of 'int (*)(struct device *, const struct device_driver *)' from incompatible pointer type 'int (*)(struct device *, struct device_driver *)' [-Werror=incompatible-pointer-types]
  283 |         .match          = span_match,
      |                           ^~~~~~~~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs.c:283:27: note: (near initialization for 'spans_bus_type.match')
make[3]: *** [scripts/Makefile.build:485: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/xpp] Error 2
make[3]: *** Waiting for unfinished jobs....
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs-chan.c:234:27: error: initialization of 'int (*)(struct device *, const struct device_driver *)' from incompatible pointer type 'int (*)(struct device *, struct device_driver *)' [-Werror=incompatible-pointer-types]
  234 |         .match          = chan_match,
      |                           ^~~~~~~~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs-chan.c:234:27: note: (near initialization for 'chan_bus_type.match')
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs.o] Error 1
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/dahdi-sysfs-chan.o] Error 1
make[2]: *** [/usr/src/linux/Makefile:1926: /usr/src/dahdi-linux-3.4.0/drivers/dahdi] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux'
make: *** [Makefile:74: modules] Error 2
```

**Comment by phoneben** [comment]
https://github.com/asterisk/dahdi-linux/issues/104
there is a new issue
