### ISSUE TITLE
Dahdi won't compile with rocky 9.5 - did with 9.3

### ISSUE THREAD

**Issue by liquidalpha** [asterisk/dahdi-linux#83]
`/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:233:27: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
  233 | DEFINE_SEMAPHORE(ifacelock);
      |                           ^
In file included from ./include/linux/fs.h:25,
                 from ./include/linux/compat.h:17,
                 from ./arch/x86/include/asm/ia32.h:8,
                 from ./arch/x86/include/asm/elf.h:10,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:19,
                 from /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:43:
./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
   34 | #define DEFINE_SEMAPHORE(_name, _n)     \
      | 
/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:233:1: warning: data definition has no type or storage class
  233 | DEFINE_SEMAPHORE(ifacelock);
      | ^~~~~~~~~~~~~~~~
/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:233:1: error: type defaults to ‘int’ in declaration of ‘DEFINE_SEMAPHORE’ [-Werror=implicit-int]
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:249: /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.o] Error 1
make[3]: *** [scripts/Makefile.build:478: /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp] Error 2
make[2]: *** [Makefile:1944: /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-503.40.1.el9_5.x86_64'
make[1]: *** [Makefile:74: modules] Error 2
make[1]: Leaving directory '/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux'
make: *** [Makefile:9: all] Error 2
`

**Comment by InterLinked1** [comment]
Additionally, I just tested this on Rocky Linux 9.5, and I can't reproduce this.

That was with all current patches, of course 3.4.0 tarball does not have them all. Likely, your issue is fixed by applying this patch: https://github.com/asterisk/dahdi-linux/pull/69/files

I'm fairly certain that will resolve your issue, in which case please go ahead and close your issue as a duplicate of #74

**Comment by karljohns0n** [comment]
To provide more information, it also builds well on 9.7, which I just did.
