### ISSUE TITLE
dhadi will not compile with Support for Linux 6.17

### ISSUE THREAD

**Issue by phoneben** [asterisk/dahdi-linux#102]
[root@pbx02 dahdi-linux]# make
make -C drivers/dahdi/firmware firmware-loaders
make[1]: Entering directory '/usr/local/src/dahdi-linux/drivers/dahdi/firmware'
make[1]: Leaving directory '/usr/local/src/dahdi-linux/drivers/dahdi/firmware'
make -C /lib/modules/6.16.7-1.el9.elrepo.x86_64/build M=/usr/local/src/dahdi-linux/drivers/dahdi DAHDI_INCLUDE=/usr/local/src/dahdi-linux/include DAHDI_MODULES_EXTRA=" " HOTPLUG_FIRMWARE=yes modules DAHDI_BUILD_ALL=m
make[1]: Entering directory '/usr/src/kernels/6.16.7-1.el9.elrepo.x86_64'
make[2]: Entering directory '/usr/local/src/dahdi-linux/drivers/dahdi'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-5)
  You are using:           gcc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-11)
  CC [M]  oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_adpcm_chan.o
oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_adpcm_chan.c:34:10: fatal error: octdef.h: No such file or directory
   34 | #include "octdef.h"
      |          ^~~~~~~~~~
compilation terminated.
make[5]: *** [/usr/src/kernels/6.16.7-1.el9.elrepo.x86_64/scripts/Makefile.build:287: oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_adpcm_chan.o] Error 1
make[4]: *** [/usr/src/kernels/6.16.7-1.el9.elrepo.x86_64/scripts/Makefile.build:555: oct612x] Error 2
make[3]: *** [/usr/src/kernels/6.16.7-1.el9.elrepo.x86_64/Makefile:2003: .] Error 2
make[2]: *** [/usr/src/kernels/6.16.7-1.el9.elrepo.x86_64/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/local/src/dahdi-linux/drivers/dahdi'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.16.7-1.el9.elrepo.x86_64'
make: *** [Makefile:74: modules] Error 2

**Comment by InterLinked1** [comment]
This is a duplicate of #76, please close this issue

This bug is fixed if you compile using PhreakScript: https://github.com/InterLinked1/phreakscript
