### ISSUE TITLE
build on alma 9.5

### ISSUE THREAD

**Issue by slesru** [asterisk/dahdi-linux#67]
Hello!

Please add 1 to semaphore parameters

/usr/src/dahdi/drivers/dahdi/wctdm24xxp/base.c:227
/usr/src/dahdi/drivers/dahdi/voicebus/voicebus.c:1138

Thank you!

**Comment by InterLinked1** [comment]
This isn't an issue, it's a proposed solution. What problem is this in response to? (compilation errors, logs would be helpful)

**Comment by ilko-t** [comment]
Dahdi 3.4.0 doesn't compile on the new rhel 9.5 kernel, likely Alma / Rocky Linux etc too with error around declaring the above constants which need 2 arguments.
Code checks kernel version and declares with either 1 or 2 arguments, but for this specific kernel seems the logic is not updated.

In general, Dahdi compatibility with 9.x RHEL kernels is extremely  poor, never had to do so many updates and DIY changes while waiting for new version. 
On rhel 6 and 7 same dahdi version just worked after recompilation across all minor versions, never had to mess with source code or update it.


In general

**Comment by InterLinked1** [comment]
> Dahdi 3.4.0 doesn't compile on the new rhel 9.5 kernel, likely Alma / Rocky Linux etc too with error around declaring the above constants which need 2 arguments. Code checks kernel version and declares with either 1 or 2 arguments, but for this specific kernel seems the logic is not updated.
> 
> In general, Dahdi compatibility with 9.x RHEL kernels is extremely poor, never had to do so many updates and DIY changes while waiting for new version. On rhel 6 and 7 same dahdi version just worked after recompilation across all minor versions, never had to mess with source code or update it.

Do you still encounter these issues when building DAHDI using PhreakScript? https://github.com/InterLinked1/phreakscript
There are several RHEL 8/9 build fixes that it includes.

More specific version info is still needed from the OP. The RHEL issues can be quite specific.

**Comment by ilko-t** [comment]
PhreakScript never worked for me to address issues when new RHEL9 minor version is released.

The issue OP is having you can easily reproduce by compiling dahdi-linux 3.4.0 on any Alma/Rocky/ RHEL 9 patched to 9.5. It's just 2 lines of code already mentioning by OP where compilation fails.

I can also provide details tomorrow if needed.

**Comment by InterLinked1** [comment]
> PhreakScript never worked for me to address issues when new RHEL9 minor version is released.
> 
> The issue OP is having you can easily reproduce by compiling dahdi-linux 3.4.0 on any Alma/Rocky/ RHEL 9 patched to 9.5. It's just 2 lines of code already mentioning by OP where compilation fails.
> 
> I can also provide details tomorrow if needed.

I think that's the information I was looking for. My CI builds only go through 9.3 at the moment, since these seem to be all that's supported as far as containers: https://hub.docker.com/_/rockylinux

I'll see if there's another way to run that in the CI, or worst case do a manual test with 9.5.

**Comment by ilko-t** [comment]
I can see docker image for Alma Linux 9.5, wouldn't it do it?

**Comment by InterLinked1** [comment]
> I can see docker image for Alma Linux 9.5, wouldn't it do it?

I see 9.5 there but may have had an issue with building DAHDI in it in the past. I'll do some more testing on that.
I'll see if I can add Alma Linux as well, since why not.

**Comment by slesru** [comment]
> This isn't an issue, it's a proposed solution. What problem is this in response to? (compilation errors, logs would be helpful)

Just try to compile, it's easy :-)

**Comment by InterLinked1** [comment]
> > This isn't an issue, it's a proposed solution. What problem is this in response to? (compilation errors, logs would be helpful)
> 
> Just try to compile, it's easy :-)

Generally speaking, if you want volunteers in the community to fix a problem for you on their own time, it's better to provide as much information as possible up front, the actual compilation error at the very least being typical, rather than expecting them to go through the work of replicating your issue for you.

I don't currently build DAHDI on non-Debian based distros in the CI since the kernel headers installed (5.14.0) don't match the running kernel version (6.8.0). I'm trying to see if there's a way I can work around this, but so far I've not been successful. Installing RHEL, Rocky Linux, and probably Alma Linux too are all a real pain and very finicky so I'm not keen to do that if I can avoid it.

**Comment by InterLinked1** [comment]
To document the original issue, these are the compiler errors received:
I'll submit a PR in a minute here.

```
  HOSTCC  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/makefw
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctc4xxp/base.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_adpcm_chan.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wct4xxp/base.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wct4xxp/vpm450m.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_channel.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_chip_open.o
In file included from ./include/linux/srcu.h:21,
                 from ./include/linux/notifier.h:16,
                 from ./arch/x86/include/asm/uprobes.h:13,
                 from ./include/linux/uprobes.h:49,
                 from ./include/linux/mm_types.h:16,
                 from ./include/linux/buildid.h:5,
                 from ./include/linux/module.h:14,
                 from /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wct4xxp/base.c:32:
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/wct4xxp/base.c: In function 'free_wc':
./include/linux/workqueue.h:694:9: warning: call to '__warn_flushing_systemwide_wq' declared with attribute warning: Please avoid flushing system-wide workqueues. [-Wattribute-warning]
  694 |         __warn_flushing_systemwide_wq();                                \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/wct4xxp/base.c:2030:9: note: in expansion of macro 'flush_scheduled_work'
 2030 |         flush_scheduled_work();
      |         ^~~~~~~~~~~~~~~~~~~~
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_chip_stats.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp/base.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_conf_bridge.o
  LD [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctc4xxp/wctc4xxp.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wcte12xp/base.o
  LD [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wct4xxp/wct4xxp.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp/xhfc.o
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp/base.c:233:27: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
  233 | DEFINE_SEMAPHORE(ifacelock);
      |                           ^
In file included from ./include/linux/fs.h:25,
                 from ./include/linux/compat.h:17,
                 from ./arch/x86/include/asm/ia32.h:8,
                 from ./arch/x86/include/asm/elf.h:10,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:19,
                 from /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp/base.c:43:
./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
   34 | #define DEFINE_SEMAPHORE(_name, _n)     \
      | 
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp/base.c:233:1: warning: data definition has no type or storage class
  233 | DEFINE_SEMAPHORE(ifacelock);
      | ^~~~~~~~~~~~~~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp/base.c:233:1: error: type defaults to 'int' in declaration of 'DEFINE_SEMAPHORE' [-Werror=implicit-int]
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:249: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp/base.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_debug.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_events.o
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c: In function 'voicebus_stop':
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c:1139:37: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
 1139 |         static DEFINE_SEMAPHORE(stop);
      |                                     ^
In file included from ./include/linux/fs.h:25,
                 from ./include/linux/compat.h:17,
                 from ./arch/x86/include/asm/ia32.h:8,
                 from ./arch/x86/include/asm/elf.h:10,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:19,
                 from ./include/linux/device/driver.h:21,
                 from ./include/linux/device.h:32,
                 from ./include/linux/pci.h:37,
                 from /usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c:32:
./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
   34 | #define DEFINE_SEMAPHORE(_name, _n)     \
      | 
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c:1139:16: error: type defaults to 'int' in declaration of 'DEFINE_SEMAPHORE' [-Werror=implicit-int]
 1139 |         static DEFINE_SEMAPHORE(stop);
      |                ^~~~~~~~~~~~~~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c:1144:15: error: 'stop' undeclared (first use in this function)
 1144 |         down(&stop);
      |               ^~~~
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c:1144:15: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c:1139:16: warning: unused variable 'DEFINE_SEMAPHORE' [-Wunused-variable]
 1139 |         static DEFINE_SEMAPHORE(stop);
      |                ^~~~~~~~~~~~~~~~
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_interrupts.o
At top level:
/usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.c:1139:16: warning: 'DEFINE_SEMAPHORE' defined but not used [-Wunused-variable]
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:249: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus/voicebus.o] Error 1
make[2]: *** [scripts/Makefile.build:478: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/voicebus] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_memory.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_miscellaneous.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_mixer.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_phasing_tsst.o
make[2]: *** [scripts/Makefile.build:478: /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wctdm24xxp] Error 2
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_playout_buf.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_remote_debug.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_tlv.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_tone_detection.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_tsi_cnct.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_tsst.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/apilib/bt/octapi_bt0.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/apilib/largmath/octapi_largmath.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/apilib/llman/octapi_llman.o
  CC [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/oct612x-user.o
  LD [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/wcte12xp/wcte12xp.o
  LD [M]  /usr/src/dahdi-linux-3.4.0/drivers/dahdi/oct612x/oct612x.o
make[1]: *** [Makefile:1944: /usr/src/dahdi-linux-3.4.0/drivers/dahdi] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-503.14.1.el9_5.x86_64'
make: *** [Makefile:74: modules] Error 2
```
