### ISSUE TITLE
dahdi-linux-complete does not compile on Rocky Linux 9.5

### ISSUE THREAD

**Issue by vhatzist** [asterisk/dahdi-linux#72]
dahdi-linux-complete does not compile on Rocky Linux 9.5, kernel is 5.14.0. The error we get is below:

******************
[...]
/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wct4xxp/base.c:2030:9: note: in expansion of macro ‘flush_scheduled_work’
 2030 |         flush_scheduled_work();
      |         ^~~~~~~~~~~~~~~~~~~~
  CC [M]  /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wct4xxp/vpm450m.o
  LD [M]  /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wct4xxp/wct4xxp.o
  CC [M]  /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctc4xxp/base.o
  LD [M]  /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctc4xxp/wctc4xxp.o
  CC [M]  /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.o
/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:233:27: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
  233 | DEFINE_SEMAPHORE(ifacelock);
      |                           ^
In file included from ./include/linux/fs.h:25,
                 from ./include/linux/compat.h:17,
                 from ./arch/x86/include/asm/ia32.h:8,
                 from ./arch/x86/include/asm/elf.h:10,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:19,
                 from /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:43:
./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
   34 | #define DEFINE_SEMAPHORE(_name, _n)     \
      |
/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:233:1: warning: data definition has no type or storage class
  233 | DEFINE_SEMAPHORE(ifacelock);
      | ^~~~~~~~~~~~~~~~
/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.c:233:1: error: type defaults to ‘int’ in declaration of ‘DEFINE_SEMAPHORE’ [-Werror=implicit-int]
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:249: /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp/base.o] Error 1
make[3]: *** [scripts/Makefile.build:478: /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi/wctdm24xxp] Error 2
make[2]: *** [Makefile:1944: /usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux/drivers/dahdi] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-503.15.1.el9_5.x86_64'
make[1]: *** [Makefile:74: modules] Error 2
make[1]: Leaving directory '/usr/src/dahdi-linux-complete-3.4.0+3.4.0/linux'
make: *** [Makefile:9: all] Error 2
******************

Is there a way to fix this?

**Comment by InterLinked1** [comment]
Please review existing issues before opening a new one. This duplicates #67.
You should close this issue as duplicate and apply the patch in #69, or use PhreakScript to fix all outstanding build issues: https://github.com/InterLinked1/phreakscript
